# Generated by Django 4.0.3 on 2022-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cab',
            field=models.CharField(default='333', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
